Running speech batch kit sanity test

diff --git a/build-pipeline.yml b/build-pipeline.yml
--- a/build-pipeline.yml
+++ b/build-pipeline.yml
@@ -42,52 +42,52 @@ stages:
     steps:
 
 # BUILD AND TEST PIPELINE TASKS
-    - task: CmdLine@2
-      displayName: Setup Python virtual environment and install required packages Python package
-      inputs:
-        script: |
-          sudo apt-get install dos2unix
-          sudo apt-get install -y python3-venv
-          python -m venv my_venv
-          source my_venv/bin/activate
-          python -m pip install --upgrade pip
-          pip install -r requirements.txt
-          pip install twine wheel
-    - task: CmdLine@2
-      displayName: Build Python package
-      inputs:
-        script: |
-          pip install joshc_repo
-          declare OLD=$(pip show joshc_repo | grep Version | cut -c10-16)
-          declare NEW=$(python setup_batchkit.py --version)
-          echo "Latest published Python package version: $OLD"
-          echo "Current Python package version: $NEW"
-          if [ "$OLD" = "$NEW" ]; then
-              echo "ERROR: Increment Python version. New Python package has same version number as published package"
-              exit 1
-          fi
-          echo "INFO: Published Python package is version $OLD. New Python package is version $NEW"
-          chmod 755 $(setupFile)
-          python $(setupFile) sdist bdist_wheel
-    - task: CmdLine@2
-      displayName: Execute Python package unit and stress tests
-      condition: always()
-      inputs:
-        script: |
-          chmod 755 run-stress-tests.py run-tests
-          dos2unix run-tests
-          ./run-tests
-          python run-stress-tests.py
-    - task: Docker@2
-      displayName: Build Docker image
-      condition: always()
-      inputs:
-        command: build
-        repository: $(imageName)
-        Dockerfile: joshc_repo_examples/speech_sdk/Dockerfile
-        containerRegistry: $(dockerRegistryServiceConnection)
-        tags: |
-          latest
+    # - task: CmdLine@2
+    #   displayName: Setup Python virtual environment and install required packages Python package
+    #   inputs:
+    #     script: |
+    #       sudo apt-get install dos2unix
+    #       sudo apt-get install -y python3-venv
+    #       python -m venv my_venv
+    #       source my_venv/bin/activate
+    #       python -m pip install --upgrade pip
+    #       pip install -r requirements.txt
+    #       pip install twine wheel
+    # - task: CmdLine@2
+    #   displayName: Build Python package
+    #   inputs:
+    #     script: |
+    #       pip install joshc_repo
+    #       declare OLD=$(pip show joshc_repo | grep Version | cut -c10-16)
+    #       declare NEW=$(python setup_batchkit.py --version)
+    #       echo "Latest published Python package version: $OLD"
+    #       echo "Current Python package version: $NEW"
+    #       if [ "$OLD" = "$NEW" ]; then
+    #           echo "ERROR: Increment Python version. New Python package has same version number as published package"
+    #           exit 1
+    #       fi
+    #       echo "INFO: Published Python package is version $OLD. New Python package is version $NEW"
+    #       chmod 755 $(setupFile)
+    #       python $(setupFile) sdist bdist_wheel
+    # - task: CmdLine@2
+    #   displayName: Execute Python package unit and stress tests
+    #   condition: always()
+    #   inputs:
+    #     script: |
+    #       chmod 755 run-stress-tests.py run-tests
+    #       dos2unix run-tests
+    #       ./run-tests
+    #       python run-stress-tests.py
+    # - task: Docker@2
+    #   displayName: Build Docker image
+    #   condition: always()
+    #   inputs:
+    #     command: build
+    #     repository: $(imageName)
+    #     Dockerfile: joshc_repo_examples/speech_sdk/Dockerfile
+    #     containerRegistry: $(dockerRegistryServiceConnection)
+    #     tags: |
+    #       latest
     - task: CmdLine@2
       displayName: Execute Speech Batch Kit sanity test
       inputs:
